### ISSUE TITLE
xfce4 crashes when exiting files-app

### ISSUE THREAD

**Issue by MarcinWieczorek** [papyros/files-app#22]
My xfce crashes to the login screen when i press the X button on the files-app. I'm building it from clion. Please tell me what information should I provide to help you fix the issue.

Also weird display bugs are occuring, like random colorful lines all around, files-app window maximized to cover whole display with repeating content of itself.

**Comment by MarcinWieczorek** [comment]
Seems to be qml-material's issue. Got the same result when exiting one of it's examples from demo/ directory.

Running on Manjaro
I think I use qt 5.5.1

**Comment by ricardomv** [comment]
how are you starting the app? can you try with `qmlscene src/app/qml/main.qml`

**Comment by MarcinWieczorek** [comment]
I'm running it with Clion's ,,run" option, building and running the project.

Same with `qmlscene src/app/qml/main.qml`

**Comment by ricardomv** [comment]
can you test with an basic .qml file for example:

```
import QtQuick 2.3
import QtQuick.Controls 1.4

ApplicationWindow {

}
```

**Comment by MarcinWieczorek** [comment]
Well, seems to be my fault, this doesn't work for me either...

This may be causing my other problems with papyros, because I can't run it. Forgive me posting this as an issue, but to be honest there's nobody to help me on gitter, irc etc. I'd love to develop the project.

**Comment by MarcinWieczorek** [comment]
This is my console output when running papyros

```
[marcin@manjaro ~]$ papyros-session 
Registered io.papyros.session D-Bus interface
papyros.session.launcher: Registered io.papyros.launcher D-Bus interface
Starting: "greenisland" "--shell io.papyros.shell"
QObject::connect: No such slot CompositorLauncher::compositorError(QProcess::ProcessError)
QObject::connect: No such slot CompositorLauncher::compositorFinished(int,QProcess::ExitStatus)
QML debugging is enabled. Only use this in a safe environment.
libEGL warning: DRI2: failed to authenticate
OS: Manjaro Linux [linux version 4.1.11-1-MANJARO]
Architecture: x86_64; features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2
Wayland version: 1.8.1
Qt version: 5.5.0
QtCompositor version: 5.5
Green Island version: 0.6.0
Environment variables:
  XDG_SEAT=seat0
  XDG_SESSION_ID=c16
  XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/marcin
  QT_XCB_GL_INTEGRATION=xcb_egl
  QT_QUICK_CONTROLS_STYLE=Material
  XDG_SESSION_DESKTOP=xfce
  XDG_MENU_PREFIX=xfce-
  XDG_CONFIG_HOME=/home/marcin/.config
  XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session6
  QT_PLATFORM_PLUGIN=Material
  XDG_RUNTIME_DIR=/run/user/1000
  XDG_CONFIG_DIRS=/etc/xdg:/etc/xdg:/etc/xdg
  QT_STYLE_OVERRIDE=gtk
  QT_QPA_PLATFORMTHEME=Material
  XDG_VTNR=7
  XDG_CURRENT_DESKTOP=Papyros
  XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
  QT_WAYLAND_DISABLE_WINDOWDECORATION=1
  XDG_DATA_HOME=/home/marcin/.local/share
  XDG_SESSION_TYPE=x11
  QSG_RENDER_LOOP=windows
  XDG_DATA_DIRS=/usr/share:/usr/local/share:/usr/share
  QT_IM_MODULE=compose
QtCompositor: Failed to initialize EGL display. There is no EGL_WL_bind_wayland_display extension.
Cannot mix incompatible Qt library (version 0x50500) with this library (version 0x50501)
Autostart: "" from "/home/marcin/.config/autostart/xfce4-clipman-plugin-autostart.desktop"
Launching "" from "/home/marcin/.config/autostart/xfce4-clipman-plugin-autostart.desktop"
papyros.session.launcher: Launched "/home/marcin/.config/autostart/xfce4-clipman-plugin-autostart.desktop" () with pid 22857
Autostart: "Blueman Applet" from "/etc/xdg/autostart/blueman.desktop"
Launching "" from "/etc/xdg/autostart/blueman.desktop"
papyros.session.launcher: Launched "/etc/xdg/autostart/blueman.desktop" (Blueman Applet) with pid 22858
Autostart: "Screen Locker" from "/etc/xdg/autostart/light-locker.desktop"
Launching "" from "/etc/xdg/autostart/light-locker.desktop"
papyros.session.launcher: Launched "/etc/xdg/autostart/light-locker.desktop" (Screen Locker) with pid 22859
Autostart: "Manjaro Settings Manager Daemon" from "/etc/xdg/autostart/manjaro-settings-manager-daemon.desktop"
Launching "" from "/etc/xdg/autostart/manjaro-settings-manager-daemon.desktop"
papyros.session.launcher: Launched "/etc/xdg/autostart/manjaro-settings-manager-daemon.desktop" (Manjaro Settings Manager Daemon) with pid 22860
Autostart: "Pulse Audio Applet" from "/etc/xdg/autostart/pa-applet.desktop"
Launching "" from "/etc/xdg/autostart/pa-applet.desktop"

** (light-locker:22859): WARNING **: Cannot open display: 
papyros.session.launcher: Launched "/etc/xdg/autostart/pa-applet.desktop" (Pulse Audio Applet) with pid 22862
Autostart: "Update Notifier" from "/etc/xdg/autostart/pamac-tray.desktop"
Launching "" from "/etc/xdg/autostart/pamac-tray.desktop"
papyros.session.launcher: Launched "/etc/xdg/autostart/pamac-tray.desktop" (Update Notifier) with pid 22863
Autostart: "PulseAudio Sound System" from "/etc/xdg/autostart/pulseaudio.desktop"
Launching "" from "/etc/xdg/autostart/pulseaudio.desktop"

(pa-applet:22862): Gtk-WARNING **: cannot open display: :0.0
Failed to create display (Connection refused)
papyros.session.launcher: Launched "/etc/xdg/autostart/pulseaudio.desktop" (PulseAudio Sound System) with pid 22864
papyros.session.launcher: Application for "/etc/xdg/autostart/light-locker.desktop" finished with exit code 1
papyros.session.launcher: Application for "/etc/xdg/autostart/manjaro-settings-manager-daemon.desktop" finished with exit code 1
papyros.session.launcher: Application for "/etc/xdg/autostart/pa-applet.desktop" finished with exit code 1
papyros.session.launcher: Application for "/etc/xdg/autostart/pamac-tray.desktop" finished with exit code 0
Failure: Module initialization failed
papyros.session.launcher: Application for "/etc/xdg/autostart/pulseaudio.desktop" finished with exit code 1
sys:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.

(blueman-applet:22858): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(blueman-applet:22858): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Traceback (most recent call last):
  File "/usr/bin/blueman-applet", line 120, in <module>
    BluemanApplet()
  File "/usr/bin/blueman-applet", line 51, in __init__
    setup_icon_path()
  File "/usr/lib/python3.5/site-packages/blueman/Functions.py", line 174, in setup_icon_path
    ic.prepend_search_path(ICON_PATH)
AttributeError: 'NoneType' object has no attribute 'prepend_search_path'
papyros.session.launcher: Application for "/etc/xdg/autostart/blueman.desktop" finished with exit code 1

```

**Comment by ricardomv** [comment]
@MarcinWieczorek check gitter
